backend:
  name: github
  repo: Net-Slayer/MordhauModsWiki
  branch: main 
  base_url: https://mordhaumaiadb-oauth.onrender.com
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow

collections:
  - label: "Main Website"
    name: "docs"
    delete: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Tagline", name: "tagline", widget: "string"}
              - label: "Actions"
                name: "actions"
                widget: "list"
                fields:
                  - {label: "Theme", name: "theme", widget: "string"}
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
  - label: "Post"
    name: "posts"
    folder: "docs/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }