# Local testing, comment out for production
local_backend: true

backend:
  name: github
  repo: Net-Slayer/MordhauModsWiki
  branch: main 
  base_url: "https://mordhaumaiadb-oauth.onrender.com"
media_folder: "docs/public/images/uploads"
public_folder: "/images/uploads"
# publish_mode: editorial_workflow
site_url: "https://Mordhau.MaiaDB.com"
logo_url: '/images/MordhauModsLogo_Large.png'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - label: 'Main Website'
    name: 'docs'
    delete: false
    files:
      - name: 'homepage'
        label: 'Homepage'
        file: docs/index.md
      # comment: 'https://vitepress.dev/reference/default-theme-home-page'
        delete: false
        fields:
          - {label: 'Name', name: 'title', widget: 'hidden', default: 'Home'} 
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'home'}
          - {label: 'TitleTemplate', name: 'titleTemplate', widget: 'hidden', default: 'false'}
          - name: 'hero'
            label: 'Hero'
            widget: 'object'
            fields:
              - {label: 'Name', name: 'name', widget: 'hidden'}
              - {label: 'Text', name: 'text', widget: 'hidden'}
              - {label: 'Tagline', name: 'tagline', widget: 'string'}
              - name: 'actions'
                label: 'Buttons'
                type_key: text
                label_singular: 'Button'
                summary: 'Button ({{theme}}): {{text}}'
                widget: 'list'
                fields:
                  - {label: 'Text', name: 'text', widget: 'string'}
                  - {label: 'Link', name: 'link', widget: 'string'}
                  - name: 'theme'
                    label: 'Theme'
                    widget: 'select'
                    options:
                      - {label: 'Main', value: 'brand'}
                      - {label: 'Alt', value: 'alt'}
                    default: 'alt'
                      
  - label: 'Posts'
    name: 'posts'
    label_singular: 'Post'
    folder: 'docs/'
    create: true
    summary: "{{title | default('<Untitled>')}} - {{path}}"
  # field: title
    filter:
      pattern: '^(?!.*index\.md$).*$'
    nested:
      depth: 4
      summary: "{{title | default('Untitled Dir')}}"
    fields:
      - label: 'Category'
        name: 'category'     
        widget: 'string'
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Meta description', name: 'description', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
    # - {label: 'CMSfilter', name: 'cms-filter', widget: 'hidden', default: '{{filename}}.{{extension}}'}